version: '3'

services:
  mongo-db:
    image: mongo:latest
    container_name: mongo-db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_DB_USR
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_DB_PWD
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

